name: Deploy telli website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IONOS_REGISTRY_TOKEN_GITHUB_PUSH: ${{ secrets.IONOS_REGISTRY_TOKEN_GITHUB_PUSH }}
  KUBERNETES_NAMESPACE: telli-website-prod

jobs:
  build-production:
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          COMMIT_HASH=${{ github.sha }}
          docker build -f Dockerfile -t telli/website:$COMMIT_HASH .
          docker tag telli/website:$COMMIT_HASH telli.cr.de-fra.ionos.com/telli/website:$COMMIT_HASH

      - name: Push Docker image to IONOS registry
        run: |
          echo "${{ secrets.IONOS_REGISTRY_TOKEN_GITHUB_PUSH }}" | docker login --username github-push --password-stdin telli.cr.de-fra.ionos.com
          COMMIT_HASH=${{ github.sha }}
          docker push telli.cr.de-fra.ionos.com/telli/website:$COMMIT_HASH

  deploy-production:
    name: Rollout production
    environment: Production
    timeout-minutes: 5
    needs: build-production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_FILE }}
          context: ""

      - name: Update Kubernetes deployment
        run: |
          COMMIT_HASH=${{ github.sha }}
          echo "Updating Kubernetes deployment with image tag $COMMIT_HASH"
          kubectl set image deployment/telli-website-prod \
            telli-website=telli.cr.de-fra.ionos.com/telli/website:$COMMIT_HASH -n $KUBERNETES_NAMESPACE \

      - name: Wait for rollout to complete
        run: |
          echo "Waiting for rollout to complete"
          kubectl rollout status deployment/telli-website-prod -n $KUBERNETES_NAMESPACE
